### ISSUE TITLE
Message in stdout

### ISSUE THREAD

**Issue by davidbrochart** [QuantStack/jupytercad#171]
This is printed to `stdout` on startup:
```
PATH_TO_FREECAD_LIBDIR not specified, using default FreeCAD version in /home/david/micromamba/envs/jupytercad/lib
```
Any way it can be written in the logging system insead?

**Comment by trungleduc** [comment]
This message comes from `FreeCAD` python binding, not sure how we can hide it.

**Comment by martinRenou** [comment]
We can probably wrap the freecad import around a stdout redirection

**Comment by trungleduc** [comment]
Thanks, i'll do it
