### ISSUE TITLE
Jupyter CAD opens to blank window in localhost from cmd line

### ISSUE THREAD

**Issue by strategos-nzr** [QuantStack/jupytercad#180]
After installing with pip into blank conda env, no gui or jupyter framework is visible on the screen after loading. 

I have no clue as to why this would be happening, given a clean conda env install presents no errors.

What would be helpful in debugging this issue?

**Comment by trungleduc** [comment]
Thank you for your feedback, indeed it's an issue with the pip package, I'm fixing it in #181.
The JupyterLab extension should work as expected.

**Comment by trungleduc** [comment]
0.2.2 release fixed the issue
