### ISSUE TITLE
Lerna error

### ISSUE THREAD

**Issue by trungleduc** [QuantStack/jupytercad#203]
`lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.`

**Comment by un4uthorized** [comment]
The "useWorkspaces" option in Lerna has been removed. Previously, this option allowed Lerna to resolve packages using the package manager workspaces configuration. However, as of the version you are using, Lerna no longer supports this option.

Try updating the lerna.json files to specify the desired packages:

```json
"useWorkspaces": true,
```

to: 

```json
"packages": [
    "packages/*"
],
```
